config/routes.rb
PalMoanalua::Application.routes.draw do
  resources :registrations do
    member do
      get 'thankyou'
    end
  end

  authenticated :user do
    root :to => 'home#volleyball'
  end
  root :to => "home#volleyball"
  
  devise_for :users
  resources :users
  
  devise_scope :user do
    get "/cnaks" => "devise/sessions#new"
  end

  match '/privacy' => "home#privacy"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

app/views/home/privacy.html.haml
%h2 Privacy Policy
%p
  This Privacy Policy governs the manner in which Moanalua Athletic Club collects, uses, maintains and discloses information collected from users (each, a "User") of the
  %a{:href => "https://palmoanalua.herokuapp.com/"} https://palmoanalua.herokuapp.com/
  website ("Site"). This privacy policy applies to the Site and all products and services offered by Moanalua Athletic Club.

%h3 Personal identification information
%p 
  We may collect personal identification information from Users in a variety of ways, including, but not limited to, when Users visit our site, fill out a form, and in connection with other activities, services, features or resources we make available on our Site. Users may be asked for, as appropriate, name, email address, mailing address, phone number. Users may, however, visit our Site anonymously. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.

%h3 Non-personal identification information
%p
  We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.

%h3 Web browser cookies
%p
  Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.

%h3 How we use collected information
%p
  Moanalua Athletic Club may collect and use Users personal information for the following purposes:
  %ul 
    %li To send periodic emails
    %li We may use the email address to send User information and updates pertaining to their registration. It may also be used to respond to their inquiries, questions, and/or other requests.

%h3 How we protect your information
%p
  We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.

%p 
  Sensitive and private data exchange between the Site and its Users happens over a SSL secured communication channel and is encrypted and protected with digital signatures.<br><br>

%h3 Sharing your personal information
%p
  We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.

%h3 Compliance with children's online privacy protection act
%p
  Protecting the privacy of the very young is especially important. For that reason, we never collect or maintain information at our Site from those we actually know are under 13, and no part of our website is structured to attract anyone under 13.<br><br>

%h3 Changes to this privacy policy
%p
  Moanalua Athletic Club has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the bottom of this page. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.<br><br>

%h3 Your acceptance of these terms
%p
  By using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.

%h3 Contacting us
%p
  If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us.
%hr
.row
  .span6
    %p This document was last updated on November 30, 2012
  .span6{:style => 'text-align:right'}
    %p 
      Privacy policy created by 
      %a{:href=>"http://www.generateprivacypolicy.com", :target=>"_blank"} Generate Privacy Policy

app/views/home/volleyball.html.haml
%h3 Moanalua Athletic Club (MAC) 2017 Volleyball Information

.alert.alert-info
  %h4.text-error
    Registration for the 2017 season is closed.
  %span.label.label-important
    ABSOLUTELY NO LATE REGISTRATIONS
- #  %p
- #    Online Registration period is 1/1/2017 - 2/2/2017
- #    %strong.text-error ABSOLUTELY NO LATE REGISTRATIONS

%h4 Registration ages are as follows:
%ol
  %li Pinto (4/30/2010 - 5/1/2008)
  %li Mustang (4/30/2008 - 5/1/2006)
  %li Bronco (4/30/2006 - 5/1/2003)

%h4 Priority for selection are as follows:
%ol
  %li Head coaches child(ren)
  %li
    Players living in the Moanalua Elementary district
    %em (proof of residency required which needs to be a utility bill addressed to legal guardian of player)
  %li
    Players who have obtained a Geographic Exception to Moanalua Elementary or Middle School
    %em (player's school schedule acceptable)
  %li All other players
  %li Players who are requesting specific days of practice and are not a head coaches child

%h4 Notification:
%p If accepted, you will be sent an email with instructions.  Please follow and submit prior to deadline or acceptance into the league will be terminated.

%p
  Contact
  = mail_to "palmoanalua@gmail.com", nil, :subject => "MAC Volleyball Question"
  %i.icon-envelope
  for questions or assistance

- #.alert.alert-warning
- #  =link_to 'Register Now!', new_registration_url, class: 'btn btn-large btn-primary'