config/routes.rb
PalMoanalua::Application.routes.draw do
  resources :registrations do
    member do
      get 'thankyou'
    end
  end

  authenticated :user do
    root :to => 'home#volleyball'
  end
  root :to => "home#volleyball"
  
  devise_for :users
  resources :users
  
  devise_scope :user do
    get "/cnaks" => "devise/sessions#new"
  end

  match '/privacy' => "home#privacy"
end

app/views/layouts/_footer.haml
.container
  %p.pagination-centered
    Moanalua Athletic Club &copy; 2017
    |
    %span.privacy
      = link_to 'Privacy Policy', privacy_path

app/views/layouts/_header.html.haml
#header.hero-unit
  .row
    .span2= image_tag("mac-logo-blue.png")
    .span9
      %h1 Moanalua Athletic Club

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "PAL Moanalua", root_path, :class => 'brand'
.nav-collapse.in.collapse{:style => "height:auto;"}
  %ul.nav
    - if user_signed_in?
      - if current_user.has_role?(:manager) || current_user.has_role?(:admin)
        - if controller.class.name =~ /^Registrations/
          %li.active
            = link_to 'Registrations', registrations_path
        -else
          %li
            = link_to 'Registrations', registrations_path
    - if user_signed_in?
      %li
        = link_to 'Logout', destroy_user_session_path, :method=>'delete'
    - if user_signed_in?
      %li
        = link_to 'Edit account', edit_user_registration_path
      - if current_user.has_role? :admin
        %li
          = link_to 'Admin', users_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "PAL Moanalua"
    %meta{:content => content_for?(:description) ? yield(:description) : "PAL Moanalua", :name => "description"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = analytics_init if Rails.env.production?
    = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    #wrap
      .navbar.navbar-fixed-top.navbar-inverse
        %nav.navbar-inner
          .container
            - if user_signed_in?
              %button.btn.btn-navbar{:data => {:toggle => :collapse, :target => '.nav-collapse'}}
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
            = render 'layouts/navigation'
      .container{:id=>"main-container"}
        = render 'layouts/header'
        #main{:role => "main"}
          .content
            .row
              .span12
                = render 'layouts/messages'
                = yield
      #push
    #footer
      = render 'layouts/footer'